### PR TITLE
Skl support

### PR DESCRIPTION
**Pull request by lsun30**
resubmit pull request

### CODE REVIEW

**Comment by srammohan** [comment]
Validated the patch on Ubuntu 15.04 with the hybrid driver installed. I was able to generate the decoded content to a file and able to play using ffplay but I was not able to play it on the screen using yamidecode.

**Comment by lsun30** [comment]
I tried command: yamidecode -i <IVF on my SKL, the program can't exit normally. I'm trying to fix.

**Comment by seanvk** [comment]
Playing on the screen is not an issue with the patch.  More than likely an issue with yamidecode player.  Once we have verified CMRT changes this will get merged by me.

**Comment by seanvk** [comment]
lgtm.

**Pull request merged**
