### PR TITLE
Autoconf and Automake Fixups

### LINKED ISSUE #19: Update cmrt -> libcmrt for package config

### PR DESCRIPTION
**Pull request by uartie**
...was doing it all wrong for libcmrt and libdrm_intel

Fixes #19

### CODE REVIEW

**Comment by chivakker** [comment]
lgtm +1

**Comment by seanvk** [comment]
lgtm +2, approved.

**Comment by jayesht** [comment]
Validated this pull request with yamidecode app.
Build goes fine but with yamidecode -i <input> -m 1 the video renders only in red-channel.

**Comment by BtbN** [comment]
For me this made the configure phase fail, because it asks pkg-config for libcmrt, but the pkg-config module it installs is named cmrt.

**Comment by chivakker** [comment]
@BtbN you need to compile cmrt with the correspondent patch which has been merged already.

**Pull request merged**
